---
title: 'title'
author: 'THE REGRESSORS'
date: 'January 14th, 2021'
output: 'pdf_document'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
collapse = TRUE,
comment = '#>',
fig.path = './figures/'
)
knitr::knit_engines$set(julia = JuliaCall::eng_juliacall)
options(JULIA_HOME = '/home/dreth/julia/bin')
```

Importing libraries:

```{r, echo=TRUE, warning=FALSE, message=FALSE}
library(dplyr)
library(ggplot2)
library(stringr)
library(gridExtra)
library(outliers)
library(PerformanceAnalytics)
library(foreach)
library(MASS)
library(e1071) 
library(VGAM)
library(caret)
library(klaR)
library(arm)
library(caTools)
library(stepPlr)
library(LiblineaR)
library(caret)
library(Epi)
library(kableExtra)
library(ROSE)
library(ResourceSelection)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
plots <- function(dataset, col, fw=FALSE, hist='default',
                  density='default' , bins='default',
                  xtick_angles='default', sep=FALSE, savefig='default', filename='./plot.png') {
    var <- dataset %>% dplyr::select(col)
    if (bins == 'default') {bins <- rep(10,2)}
    if (xtick_angles == 'default') {xtick_angles <- rep(90,2)}
    if (hist == 'default') {hist <- c(FALSE,FALSE)}
    if (density == 'default') {density <- c(TRUE,TRUE)}
    if (savefig == 'default') {savefig <- c(FALSE,14,14)}

    p1 <- dataset %>% ggplot(aes(x=var[,1])) +
        geom_boxplot() +
        ggtitle(str_interp("${col}")) +
        theme(axis.title.x=element_blank(),axis.text.y=element_blank())
    p2 <- dataset %>% ggplot(aes(x=var[,1], fill=response)) +
        geom_boxplot() +
        ggtitle(str_interp("${col} grouped by response")) +
        theme(axis.title.x=element_blank(),axis.text.y=element_blank())
    p3 <- dataset %>% ggplot(aes(x=var[,1])) +
        ggtitle(str_interp("${col}")) +
        theme(axis.title.x=element_blank(),
                axis.text.x = element_text(angle = xtick_angles[1]))
    p4 <- dataset %>% ggplot(aes(x=var[,1])) +
        ggtitle(str_interp("${col} by response group")) +
        theme(axis.title.x=element_blank(),
                axis.text.x = element_text(angle = xtick_angles[2]))
    if (hist[1] == TRUE) {
        p3 <- p3 + geom_histogram(aes(y=..density..),bins=bins[1])}
    if (hist[2] == TRUE) {
        p4 <- p4 + geom_histogram(show.legend = FALSE,bins=bins[2],
                                  aes(fill=response,y=..density..))}
    if (density[1] == TRUE) {
        p3 <- p3 + geom_density()}
    if (density[2] == TRUE) {
        p4 <- p4 + geom_density(aes(group=response,colour=response,fill=response))}
    if (fw == TRUE) {p4 <- p4 + facet_wrap(~response, nrow = 1)}
    if (sep == TRUE) {
        grid.arrange(p1,p2, nrow=2)
        grid.arrange(p3,p4, nrow=2)}
    else {grid.arrange(p1,p2,p3,p4, nrow=4)}
    if (savefig[1] == TRUE) {ggsave(file=filename, width=savefig[2], height=savefig[3],
                                 arrangeGrob(p1,p2,p3,p4, nrow=4))}
}
```

Importing and manipulating the data:

```{r, echo=TRUE, warning=FALSE, message=FALSE}
credit <- read.csv('./data/credit.csv')
names(credit) <- tolower(names(credit))
set.seed(1)
```

TTS:

```{r, echo=TRUE, warning=FALSE, message=FALSE}
spl = createDataPartition(credit$response, p = 0.7, list = FALSE)
Train = credit[spl,]
Test = credit[-spl,]
```

Create formulas function:

```{r, echo=TRUE, warning=FALSE, message=FALSE}
model_formula <- function(data, combs, target, with_int=TRUE, all=FALSE) {
    formulas <- c()
    cols <- names(data)[2:(length(names(data))-1)]
    combinations <- combinat::combn(cols, combs)
    for (i in 1:length(combinations[1,])) {
        if (with_int == TRUE) {
            if (all == TRUE) {
                form_pst <- paste(combinations[,i], collapse="*")
                form <- stringr::str_interp("${target}~${form_pst}")
                formulas <- c(formulas, form)
            } else {
                form_pst <- paste(combinations[,i], collapse="+")
                form <- stringr::str_interp("${target}~(${form_pst})^${all}")
                formulas <- c(formulas, form)
            }
        } else {
            form_pst <- paste(combinations[,i], collapse="+")
            form <- stringr::str_interp("${target}~${form_pst}")
            formulas <- c(formulas, form)
        }
    }
    return(formulas)
}
forms <- model_formula(Train, 2, "response", with_int=TRUE, all=2)
```

Modelling function:

```{r, echo=TRUE, warning=FALSE, message=FALSE}
modelling <- function(data, formulas) {
    models <- list()
    for (i in 1:length(formulas)) {
        models[[i]] <- glm(formula=formulas[i], family=binomial, data=data)
    }
    return(models)
}
models <- modelling(Train, forms)
```


LRT for models with and without interactions:

```{r, echo=TRUE, warning=FALSE, message=FALSE}
test <- function(formulas_with, formulas_without, models_with_int, models_without_int) {
    p_vals <- c()
    for (i in 1:length(formulas_with)) {
        p_vals <- c(p_vals, anova(models_with_int[[i]], models_without_int[[i]], test="Chisq")$"Pr(>Chi)"[2])
    }
    return(data.frame(formulas_with=formulas_with, formulas_without=formulas_without, pvals=p_vals))
}
formulas_with <- model_formula(Train, 3, "response", with_int=TRUE, all=3)
formulas_without <- model_formula(Train, 3, "response", with_int=FALSE)
models_with <- modelling(Train, formulas_with)
models_without <- modelling(Train, formulas_without)
```

Scoring function:

```{r, echo=TRUE, warning=FALSE, message=FALSE}
scoring <- function(data, testing, models, formulas) {
    accuracy <- c()
    roc_cutoff <- c()
    roc_auc <- c()
    roc_sensitivity <- c()
    roc_specificity <- c()
    # hoslem <- c()
    for (i in 1:length(models)) {
        # ROC curve
        roc1 <- Epi::ROC(form=formula(models[[i]]), data=data, plot="ROC", lw=3, cex=1.5)
        cutoff <- which.max(rowSums(roc1$res[, c("sens", "spec")]))

        # ROC params
        roc_cutoff <- c(roc_cutoff, roc1$res$lr.eta[cutoff])
        roc_auc <- c(roc_auc, roc1$AUC)
        roc_sensitivity <- c(roc_sensitivity, roc1$res$sens[cutoff])
        roc_specificity <- c(roc_specificity, roc1$res$spec[cutoff])

        # prediction using BEST cutoff
        prediction <- predict(models[[i]], newdata=testing, type="response")
        prediction <- ifelse(prediction > roc1$res$lr.eta[cutoff], 1, 0)
        pred <- as.factor(prediction)

        # target score 
        real_vals <- as.factor(testing$response)

        # hosmer lemeshow goodness of fit test
        # hltest <- hoslem.test(real_vals, prediction)$p.value
        # hoslem <- c(hoslem, hltest)

        # confusion matrix score
        accuracy <- c(accuracy,confusionMatrix(pred, real_vals)$overall[1])
    }
    return(data.frame(formula=formulas,
                      accuracy=accuracy, 
                      cutoff=roc_cutoff, 
                      roc_auc=roc_auc, 
                      sensitivity=roc_sensitivity, 
                      specificity=roc_specificity))
}
```

Transforming all categorical variables to factor:

```{r, echo=TRUE, warning=FALSE, message=FALSE}
vars <- c("obs.","chk_acct","duration","history",
          "new_car","used_car","furniture","radio.tv",
          "education","retraining","amount","sav_acct",
          "employment","install_rate","male_div","male_single",
          "male_mar_or_wid","co.applicant","guarantor","present_resident",
          "real_estate","prop_unkn_none","age","other_install",
          "rent","own_res","num_credits","job",
          "num_dependents","telephone","foreign","response")
vars_to_remove <- c("own_res", "obs", "real_estate","response")
credit$response <- as.factor(credit$response)
names(credit)
```

```{r, echo=TRUE, warning=FALSE, message=FALSE}
plt <- function(col) {
    print(col)
    var <- credit %>% dplyr::select(col)
    ggplot(credit, aes(y=var[,1], fill=response)) + geom_bar()
}

plt('co.applicant')
plt('guarantor')
```

1-variable models:

```{r, echo=TRUE, warning=FALSE, message=FALSE}
cols <- names(credit)[2:(length(names(credit))-1)]
vars <- c()
acc <- c()
for (i in 1:length(cols)) {
    # formula and model
    form <- stringr::str_interp("response~${cols[i]}")
    mod <- glm(formula=form, family=binomial, data=Train)
    form <- formula(mod)

    # ROC curve and cutoff
    roc1 <- Epi::ROC(form=form, data=Train, plot="ROC", lw=3, cex=1.5)
    cutoff <- roc1$res$lr.eta[2]

    # prediction
    pred <- predict(mod, newdata=Test, type="response")
    pred <- ifelse(pred > cutoff, 1, 0)
    pred <- as.factor(pred)

    # confusion matrix and accuracy
    Accuracy <- confusionMatrix(pred, Test$response)$overall[1]
    
    # adding variables to prediction
    vars <- c(vars, cols[i])
    acc <- c(acc, Accuracy)
}
df <- data.frame(vars=vars, accuracy=acc)
write.csv(df[order(df$accuracy),], './outputs/1_var_models.csv')
```

Checking 2-variable models and interactions:







```{r, echo=TRUE, warning=FALSE, message=FALSE}
cool_stuff <- test(formulas_with, formulas_without, models_with, models_without)
cool_stuff <- na.omit(cool_stuff[order(-cool_stuff$pvals),])
cool_stuff <- cool_stuff[cool_stuff$pvals < 0.01,]
write.csv(cool_stuff, "./outputs/3_var_models_LRT_01.csv")

scrs <- scoring(Train, Test, models_with, formulas_with)
write.csv(scrs, "./outputs/3_val_scores_with.csv")

```

```{r, echo=TRUE, warning=FALSE, message=FALSE}
cool_stuff <- na.omit(cool_stuff[cool_stuff$pvals < 0.02,])
model_numbers <- as.numeric(rownames(cool_stuff))
all_vars <- list()
for (i in 1:length(model_numbers)) {
    all_vars[[i]] <- all.vars(formula(models_with[[model_numbers[i]]])[-2])
    all_vars[[i]] <- c(all_vars[[i]], paste(all_vars[[i]],collapse=":"))
}
vars <- c()
for (i in 1:length(all_vars)) {
    vars <- c(vars, all_vars[[i]][1])
}

test_model <- glm(form=str_interp("response~(${paste(vars, collapse='+')})^2"), family=binomial, data=Train)
staic <- stepAIC(test_model)
```

```{r, echo=TRUE, warning=FALSE, message=FALSE}
scores <- read.csv('./outputs/scores_with.csv')
scores_without <- read.csv('./outputs/scores_without.csv')
p_value <- read.csv('./outputs/2_var_models_LRT.csv')
scores = scores %>% rename("formulas_with"="formula")
a = merge(p_value, scores, by = "formulas_with")

scores_without = scores_without %>% rename("formulas_without"="formula")
b = merge(a,scores_without, by =  "formulas_without")
cool_stuff_2 <- b[b$accuracy.x>0.68,]
model_numbers <- as.numeric(rownames(cool_stuff_2))
all_vars <- list()
for (i in 1:length(model_numbers)) {
    all_vars[[i]] <- all.vars(formula(models_with[[model_numbers[i]]])[-2])
    all_vars[[i]] <- c(all_vars[[i]], paste(all_vars[[i]],collapse=":"))
}
vars <- c()
for (i in 1:length(all_vars)) {
    vars <- c(vars, all_vars[[i]][1])
}
vars <- unique(vars)

test_model <- glm(form=str_interp("response~${paste(vars, collapse='+')}"), family=binomial, data=Train)
staic <- stepAIC(test_model)

roc1 <- Epi::ROC(form=formula(staic), data=Train, plot="ROC", lw=3, cex=1.5)
cutoff <- which.max(rowSums(roc1$res[, c("sens", "spec")]))

prediction <- predict(staic, newdata=Test, type="response")
prediction <- ifelse(prediction > roc1$res$lr.eta[cutoff], 1, 0)
pred <- as.factor(prediction)
real_vals <- Test$response
confusionMatrix(pred, real_vals)

credit_2 <- credit %>% dplyr::select(vars)
```

```{r, echo=TRUE, warning=FALSE, message=FALSE}
df <- data.frame(vars=vars, accuracy=acc)
df[order(df$accuracy),]
```